### ISSUE TITLE
Adding alumni table widget

### ISSUE THREAD

**Issue by patrik-bartak** [SERG-Delft/serg-www#4]
Add widget that allows for formatting members in a table as alumni

**Comment by mitchellolsthoorn** [comment]
As a reference and starting point, you can use the following file: https://github.com/wowchemy/wowchemy-hugo-themes/blob/main/wowchemy/layouts/partials/widgets/people.html

This file needs to be adapted to use a table format using the Bootstrap v4 table styles.

For the columns, we can use the same values as the old website:
- Name (link to author page)
- Period
- Role
- Current Affiliation
